### ISSUE TITLE
TODO: Remove TransactionBuilder

### ISSUE THREAD

**Issue by junderw** [bitcoinjs/bitcoinjs-lib#1477]

**Comment by ildarmgt** [comment]
Hi. Big fan of library.

Will there be another simplified solution or only psbt?

Specifically, for non-segwit inputs, we always have to fetch a full raw tx for every input? I managed to replicate majority of functions, but since I mostly use arbitrary scripts for everything (found psbt [csv example](https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/integration/csv.spec.ts) for finalizing inputs to adopt to arb scripts) and random mixtures of old and new types of addresses, never multisigs, I was wondering if it's possible to simulate how the old transaction builder worked with psbt without raw tx if we're not benefiting from the partially signed format? 

It's usually 5x+ extra api or full node calls and delay for data not normally available to light clients unlike txid/vout/script we tend to know.

I'll make it work either way, but was just curious if I missed something obvious on how to minimize amount of data fetching, storage, and transfer back and forth to generate tx from cold wallets or on light clients.

Once again, thanks for the great work.

**Comment by junderw** [comment]
It is possible to remove the requirement of full transaction (for nonsegwit) and previous script (for segwit) by assuming the script based off of the private key used for signing.

However, the whole point of PSBT is to be interoperable with other implementations, and the spec requires the full tx for each nonsegwit input.

TransactionBuilder is weak against malicious fee manipulation attacks where your app's view of its utxos is warped to trick you into spending a larger amount than you wanted, stealing the fees.

By requiring and checking the previous tx and the amount, this is prevented.

**Comment by motorina0** [comment]
- [x] remove `TransactionBuilder`
- [x] remove non-public dependecies of `TransactionBuilder` (can only be accessed via `TransactionBuilder`):
  - `./classify`
    - `./templates/multisig`
    - `./templates/nulldata`
    - `./templates/pubkey`
    - `./templates/pubkeyhash`
    - `./templates/scripthash`
    - `./templates/witnesscommitment`
    - `./templates/witnesspubkeyhash`
    - `./templates/witnessscripthash`
- [x] remove text references to `TransactionBuilder` (in PSBT refernces are made to the now removed `TransactionBuilder`)
- [x] move test data from `templates.json` to `scripts.json`
   - remove `templates.json`
   - update `script.spec.ts`

**Comment by Generalsuki02** [comment]
Add to this 6.0.0
